Repository tatd3v/bm-website, pull requests merged in 2024-04, with the labels that each got.

#20 Feat/react router
  lalala.md
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.jsx
  src/app/slides/dataSlide.js
  src/app/slides/uiSlide.js
  src/components/Dictionary/Dictionary.jsx
  src/components/Gallery/EventGallery.jsx
  src/components/Gallery/index.js
  src/components/Header/Header.jsx
  src/components/Header/SubNavbar/SubNavbar.jsx
  src/components/Header/SubNavbar/subNavbar.scss
  src/components/backgroundVideo/BackgroundVideo.jsx
  src/components/backgroundVideo/backgroundVideo.scss
  src/helpers/eventsData.js
  src/helpers/extractNumbersFromString.js
  src/helpers/groupByArray.js
  src/helpers/index.js
  src/index.css
  src/main.jsx
  src/pages/Error/Error.jsx
  src/pages/Error/error.css
  src/pages/Error/index.js
  src/pages/Gallery/GalleryByBall.jsx
  src/pages/Gallery/Photos.jsx
  src/pages/Gallery/Videos.jsx
  src/pages/Gallery/index.js
  src/pages/Home/Home.jsx
  src/pages/Home/index.js
  src/pages/Layouts/GalleryLayout.jsx
  src/pages/Layouts/RootLayout.jsx
  src/pages/Layouts/index.js
  src/pages/index.js
  src/routes/GalleryRoutes.jsx
  src/template/GalleryPhotos.jsx
  src/template/GalleryVideos.jsx
  src/template/index.js
  vite.config.js
Labels: feature

#22 Sticky buttons
  src/app/index.js
  src/app/slides/dataSlide.js
  src/app/slides/index.js
  src/assets/images/igTransparentLogo.png
  src/assets/images/index.js
  src/assets/images/ttTransparentLogo.png
  src/assets/images/ytTransparentLogo.png
  src/components/BottomSticky/StickyIcon.jsx
  src/components/BottomSticky/StickyNav.jsx
  src/components/BottomSticky/iconsData.js
  src/components/BottomSticky/index.js
  src/components/BottomSticky/stickyIcon.scss
  src/components/BottomSticky/stickyNav.scss
  src/components/index.js
  src/pages/Layouts/RootLayout.jsx
Labels: feature

#23 create vercel json file at root
  .gitignore
  vercel.json
Labels: config

#26 Fix sticky icons position
  src/assets/ShortLogoWhite.png
  src/assets/images/igTransparentLogo.png
  src/assets/images/ttTransparentLogo.png
  src/assets/images/ytTransparentLogo.png
  src/components/BottomSticky/index.js
  src/components/BottomSticky/stickyIcon.scss
  src/components/BottomSticky/stickyNav.scss
  src/components/Header/Header.jsx
  src/components/Header/SocialMediaNavBar/SocialMediaIcon.jsx
  src/components/Header/SocialMediaNavBar/SocialMediaNav.jsx
  src/components/Header/SocialMediaNavBar/iconsData.js
  src/components/Header/SocialMediaNavBar/index.js
  src/components/Header/SocialMediaNavBar/socialMediaIcon.scss
  src/components/Header/SocialMediaNavBar/socialMediaNav.scss
  src/components/index.js
  src/pages/Layouts/RootLayout.jsx
Labels: fix

#28 Change youtube logo position
  src/components/Header/SocialMediaNavBar/socialMediaNav.scss
Labels: fix

#29 Develop into Main merge
  src/components/Header/SocialMediaNavBar/socialMediaNav.scss
Labels: fix

#30 Web radio
  .env
  package.json
  pnpm-lock.yaml
  src/app/index.js
  src/app/slides/index.js
  src/app/slides/uiSlide.js
  src/assets/index.js
  src/assets/voguerLoader.gif
  src/components/Footer/Footer.jsx
  src/components/Footer/footer.scss
  src/components/Footer/index.js
  src/components/Header/SocialMediaNavBar/socialMediaNav.scss
  src/components/LiveRadio/LiveRadio.jsx
  src/components/LiveRadio/index.js
  src/components/LiveRadio/liveRadio.scss
  src/components/Loading/Loading.jsx
  src/components/Loading/LoadingWord.jsx
  src/components/Loading/index.js
  src/components/Loading/loading.scss
  src/components/Loading/loadingWords.scss
  src/components/index.js
  src/index.css
  src/pages/Error/Error.jsx
  src/pages/Layouts/RootLayout.jsx
Labels: feature

#31 Develop merge to Main
  .env
  package.json
  pnpm-lock.yaml
  src/app/index.js
  src/app/slides/index.js
  src/app/slides/uiSlide.js
  src/assets/index.js
  src/assets/voguerLoader.gif
  src/components/Footer/Footer.jsx
  src/components/Footer/footer.scss
  src/components/Footer/index.js
  src/components/Header/SocialMediaNavBar/socialMediaNav.scss
  src/components/LiveRadio/LiveRadio.jsx
  src/components/LiveRadio/index.js
  src/components/LiveRadio/liveRadio.scss
  src/components/Loading/Loading.jsx
  src/components/Loading/LoadingWord.jsx
  src/components/Loading/index.js
  src/components/Loading/loading.scss
  src/components/Loading/loadingWords.scss
  src/components/index.js
  src/index.css
  src/pages/Error/Error.jsx
  src/pages/Layouts/RootLayout.jsx
Labels: release

#32 modify radio widget url
  .env
  src/components/LiveRadio/LiveRadio.jsx
Labels: fix

#33 Develop
  .env
  src/components/LiveRadio/LiveRadio.jsx
Labels: release

#34 modify widow innerwith to 991
  src/App.jsx
Labels: fix

#36 Fix/show in ios safari
  package.json
  pnpm-lock.yaml
  src/components/Footer/footer.scss
  src/components/Header/Header.jsx
  src/components/Header/SocialMediaNavBar/socialMediaNav.scss
  src/components/Header/header.scss
  src/components/LiveRadio/LiveRadio.jsx
Labels: fix

#37 Develop
  package.json
  pnpm-lock.yaml
  src/components/Footer/footer.scss
  src/components/Header/Header.jsx
  src/components/Header/SocialMediaNavBar/socialMediaNav.scss
  src/components/Header/header.scss
  src/components/LiveRadio/LiveRadio.jsx
Labels: release

#38 FIX header toggle button subnavbar collapse
  .eslintignore
  .eslintrc.js
  .gitignore
  index.html
  package.json
  pnpm-lock.yaml
  src/components/Header/Header.jsx
  src/components/Header/SocialMediaNavBar/SocialMediaIcon.jsx
  src/components/Header/SocialMediaNavBar/SocialMediaNav.jsx
  src/components/Header/SocialMediaNavBar/_socialMediaIcon.scss
  src/components/Header/SocialMediaNavBar/_socialMediaNav.scss
  src/components/Header/SubNavbar/SubNavbar.jsx
  src/components/Header/SubNavbar/index.js
  src/components/Header/_header.scss
  src/components/Header/header.scss
  src/index.css
  src/main.jsx
  src/styles/_colors.scss
  src/styles/_fonts.scss
  src/styles/_index.scss
  src/styles/index.js
Labels: fix
